//
// This source file is part of the OncoWell application.
//
// SPDX-FileCopyrightText: 2026 Stanford University
//
// SPDX-License-Identifier: MIT
//

import Foundation


enum CaregiverSummaryGenerator {
    struct Options {
        var includeSymptoms = true
        var includeTestResults = true
        var includeAppointments = true
        var includeVisitNotes = true
        var includeQuestions = true
    }

    private static var header: String {
        let formatter = DateFormatter()
        formatter.dateStyle = .long
        let dateString = formatter.string(from: Date.now)
        return "ONCOWELL CARE UPDATE\n\(dateString)\n" + String(repeating: "─", count: 30)
    }

    private static var footer: String {
        String(repeating: "─", count: 30)
            + "\nGenerated by OncoWell — all data stays on-device."
            + "\nPlease discuss any concerns with the care team."
    }

    static func generate(
        symptoms: [SymptomLogEntry],
        testResults: [TestResult],
        appointments: [Appointment],
        visitNotes: [DoctorVisitNote],
        options: Options
    ) -> String {
        var sections: [String] = []

        sections.append(header)

        if options.includeSymptoms {
            sections.append(symptomSection(symptoms))
        }
        if options.includeTestResults {
            sections.append(testResultSection(testResults))
        }
        if options.includeAppointments {
            sections.append(appointmentSection(appointments))
        }
        if options.includeVisitNotes {
            sections.append(visitNoteSection(visitNotes))
        }
        if options.includeQuestions {
            let upcoming = appointments.filter { $0.status == .upcoming }
            sections.append(questionSection(upcoming))
        }

        sections.append(footer)
        return sections.joined(separator: "\n\n")
    }

    private static func symptomSection(_ symptoms: [SymptomLogEntry]) -> String {
        var lines = ["RECENT SYMPTOMS"]
        let recent = Array(symptoms.prefix(10))
        if recent.isEmpty {
            lines.append("  No symptoms logged.")
        } else {
            for symptom in recent {
                let date = formatDate(symptom.date)
                var line = "  • \(symptom.symptomType.rawValue) — \(symptom.severity.label) (\(date))"
                if !symptom.bodyLocation.isEmpty {
                    line += " — \(symptom.bodyLocation)"
                }
                lines.append(line)
            }
        }
        return lines.joined(separator: "\n")
    }

    private static func testResultSection(_ results: [TestResult]) -> String {
        var lines = ["RECENT TEST RESULTS"]
        let recent = Array(results.prefix(10))
        if recent.isEmpty {
            lines.append("  No test results logged.")
        } else {
            for result in recent {
                let date = formatDate(result.date)
                var line = "  • \(result.testName): \(result.value)"
                if !result.unit.isEmpty {
                    line += " \(result.unit)"
                }
                line += " (\(date))"
                if !result.referenceRange.isEmpty {
                    line += " [ref: \(result.referenceRange)]"
                }
                lines.append(line)
            }
        }
        return lines.joined(separator: "\n")
    }

    private static func appointmentSection(_ appointments: [Appointment]) -> String {
        var lines = ["UPCOMING APPOINTMENTS"]
        let upcoming = appointments
            .filter { $0.status == .upcoming }
            .sorted { $0.date < $1.date }
        if upcoming.isEmpty {
            lines.append("  No upcoming appointments.")
        } else {
            for appt in upcoming.prefix(5) {
                let date = formatDateTime(appt.date)
                var line = "  • \(appt.appointmentType.rawValue) — \(date)"
                if !appt.providerName.isEmpty {
                    line += " with \(appt.providerName)"
                }
                if !appt.facilityName.isEmpty {
                    line += " at \(appt.facilityName)"
                }
                lines.append(line)
            }
        }
        return lines.joined(separator: "\n")
    }

    private static func visitNoteSection(_ notes: [DoctorVisitNote]) -> String {
        var lines = ["RECENT VISIT NOTES"]
        let recent = Array(notes.prefix(5))
        if recent.isEmpty {
            lines.append("  No visit notes recorded.")
        } else {
            for note in recent {
                let date = formatDate(note.date)
                var line = "  • \(note.visitType.rawValue) (\(date))"
                if !note.providerName.isEmpty {
                    line += " — \(note.providerName)"
                }
                lines.append(line)
                if !note.summary.isEmpty {
                    lines.append("    Summary: \(note.summary)")
                }
                if !note.decisionsAndNextSteps.isEmpty {
                    lines.append("    Next steps: \(note.decisionsAndNextSteps)")
                }
            }
        }
        return lines.joined(separator: "\n")
    }

    private static func questionSection(_ upcoming: [Appointment]) -> String {
        var lines = ["QUESTIONS FOR NEXT VISIT"]
        let allQuestions = upcoming.flatMap { $0.questions.filter { !$0.isAsked } }
        if allQuestions.isEmpty {
            lines.append("  No pending questions.")
        } else {
            for question in allQuestions {
                lines.append("  • \(question.text)")
            }
        }
        return lines.joined(separator: "\n")
    }

    private static func formatDate(_ date: Date) -> String {
        let formatter = DateFormatter()
        formatter.dateStyle = .medium
        return formatter.string(from: date)
    }

    private static func formatDateTime(_ date: Date) -> String {
        let formatter = DateFormatter()
        formatter.dateStyle = .medium
        formatter.timeStyle = .short
        return formatter.string(from: date)
    }
}
