//
// This source file is part of the OncoWell application.
//
// SPDX-FileCopyrightText: 2026 Stanford University
//
// SPDX-License-Identifier: MIT
//

import SwiftData
import SwiftUI


struct TranscriptSummaryView: View {
    @Environment(\.modelContext) private var modelContext
    @Bindable var recording: AppointmentRecording

    @State private var isGenerating = false
    @State private var errorMessage: String?


    var body: some View {
        ScrollView {
            VStack(alignment: .leading, spacing: 20) {
                aiDisclaimer
                if let summary = recording.summary {
                    summaryContent(summary)
                } else if isGenerating {
                    generatingIndicator
                } else if TranscriptIntelligenceService.isAvailable {
                    generatePrompt
                } else {
                    unavailableMessage
                }
            }
            .padding()
        }
        .navigationTitle("Summary")
        .navigationBarTitleDisplayMode(.inline)
        .alert("Error", isPresented: showingError) {
            Button("OK") { errorMessage = nil }
        } message: {
            Text(errorMessage ?? "")
        }
    }

    private var showingError: Binding<Bool> {
        Binding(
            get: { errorMessage != nil },
            set: { if !$0 { errorMessage = nil } }
        )
    }

    private var aiDisclaimer: some View {
        HStack(spacing: 8) {
            Image(systemName: "sparkles")
                .foregroundStyle(.purple)
                .accessibilityHidden(true)
            Text(disclaimerText)
                .font(.caption)
                .foregroundStyle(.secondary)
        }
        .padding()
        .background(Color.purple.opacity(0.08))
        .clipShape(RoundedRectangle(cornerRadius: 10))
    }

    private var disclaimerText: String {
        "This summary was generated by on-device AI. "
        + "It may contain errors or miss important details. "
        + "Always verify with your healthcare provider."
    }

    private var generatingIndicator: some View {
        VStack(spacing: 12) {
            ProgressView()
                .scaleEffect(1.5)
            Text("Analyzing transcript...")
                .font(.headline)
            Text("This happens entirely on your device.")
                .font(.caption)
                .foregroundStyle(.secondary)
        }
        .frame(maxWidth: .infinity)
        .padding(.vertical, 40)
    }

    private var generatePrompt: some View {
        VStack(spacing: 12) {
            Image(systemName: "sparkles")
                .font(.system(size: 40))
                .foregroundStyle(.purple)
                .accessibilityHidden(true)
            Text("Generate Summary")
                .font(.title3)
                .fontWeight(.semibold)
            Text(generateExplanation)
                .font(.body)
                .foregroundStyle(.secondary)
                .multilineTextAlignment(.center)
            Button(action: generateSummary) {
                Label("Analyze Transcript", systemImage: "sparkles")
                    .font(.headline)
                    .frame(maxWidth: .infinity)
            }
            .buttonStyle(.borderedProminent)
            .tint(.purple)
        }
    }

    private var generateExplanation: String {
        "Use on-device AI to generate a plain-language summary, "
        + "extract key decisions, next steps, and medications discussed."
    }

    private var unavailableMessage: some View {
        VStack(spacing: 12) {
            Image(systemName: "exclamationmark.triangle")
                .font(.system(size: 40))
                .foregroundStyle(.secondary)
                .accessibilityHidden(true)
            Text("AI Summary Unavailable")
                .font(.headline)
            Text(unavailableExplanation)
                .font(.body)
                .foregroundStyle(.secondary)
                .multilineTextAlignment(.center)
        }
        .frame(maxWidth: .infinity)
        .padding(.vertical, 20)
    }

    private var unavailableExplanation: String {
        "On-device AI is not available on this device. "
        + "You can still view the full transcript."
    }

    private var regenerateButton: some View {
        Button {
            if let existing = recording.summary {
                modelContext.delete(existing)
            }
            generateSummary()
        } label: {
            Label("Regenerate Summary", systemImage: "arrow.clockwise")
        }
        .frame(maxWidth: .infinity)
    }

    private func summaryContent(_ summary: TranscriptSummary) -> some View {
        VStack(alignment: .leading, spacing: 20) {
            summarySection(summary.plainLanguageSummary)
            topicSection("Decisions", items: summary.decisions, icon: "checkmark.circle", color: .green)
            topicSection("Next Steps", items: summary.nextSteps, icon: "arrow.forward.circle", color: .blue)
            topicSection("Medications", items: summary.medicationsDiscussed, icon: "pill", color: .orange)
            topicSection("Follow-Up", items: summary.followUpInstructions, icon: "calendar.circle", color: .purple)
            annotationsSection(summary)
            regenerateButton
        }
    }

    private func summarySection(_ text: String) -> some View {
        VStack(alignment: .leading, spacing: 8) {
            Text("Summary")
                .font(.headline)
            Text(text)
                .font(.body)
        }
        .padding()
        .frame(maxWidth: .infinity, alignment: .leading)
        .background(.background)
        .clipShape(RoundedRectangle(cornerRadius: 12))
        .shadow(color: .black.opacity(0.05), radius: 2, y: 1)
    }

    private func topicSection(
        _ title: String,
        items: [String],
        icon: String,
        color: Color
    ) -> some View {
        Group {
            if !items.isEmpty {
                VStack(alignment: .leading, spacing: 8) {
                    Label(title, systemImage: icon)
                        .font(.headline)
                        .foregroundStyle(color)
                    ForEach(items, id: \.self) { item in
                        HStack(alignment: .top, spacing: 8) {
                            Text("•")
                                .foregroundStyle(color)
                            Text(item)
                                .font(.body)
                        }
                    }
                }
                .padding()
                .frame(maxWidth: .infinity, alignment: .leading)
                .background(.background)
                .clipShape(RoundedRectangle(cornerRadius: 12))
                .shadow(color: .black.opacity(0.05), radius: 2, y: 1)
            }
        }
    }

    private func annotationsSection(_ summary: TranscriptSummary) -> some View {
        VStack(alignment: .leading, spacing: 8) {
            Text("Your Notes")
                .font(.headline)
            TextField(
                "Add corrections or notes about this summary",
                text: Bindable(summary).userAnnotations,
                axis: .vertical
            )
            .lineLimit(3...8)
            .font(.body)
        }
        .padding()
        .frame(maxWidth: .infinity, alignment: .leading)
        .background(.background)
        .clipShape(RoundedRectangle(cornerRadius: 12))
        .shadow(color: .black.opacity(0.05), radius: 2, y: 1)
    }

    private func generateSummary() {
        isGenerating = true
        Task {
            do {
                let result = try await TranscriptIntelligenceService.analyze(
                    transcript: recording.transcriptText
                )
                await MainActor.run {
                    saveSummary(from: result)
                    isGenerating = false
                }
            } catch {
                await MainActor.run {
                    isGenerating = false
                    errorMessage = "Failed to generate summary: \(error.localizedDescription)"
                }
            }
        }
    }

    private func saveSummary(from result: TranscriptSummaryResult) {
        let summary = TranscriptSummary(
            plainLanguageSummary: result.summary,
            decisions: result.decisions,
            nextSteps: result.nextSteps,
            medicationsDiscussed: result.medicationsDiscussed,
            followUpInstructions: result.followUpInstructions,
            recording: recording
        )
        modelContext.insert(summary)
    }
}
