//
// This source file is part of the OncoWell application.
//
// SPDX-FileCopyrightText: 2026 Stanford University
//
// SPDX-License-Identifier: MIT
//

import SwiftUI


// swiftlint:disable:next file_types_order
struct TranscriptView: View {
    let recording: AppointmentRecording
    @State private var selectedTerm: GlossaryTerm?


    var body: some View {
        ScrollView {
            VStack(alignment: .leading, spacing: 20) {
                disclaimer
                summaryLink
                if sortedSegments.isEmpty {
                    fullTranscriptSection
                } else {
                    segmentsSection
                }
            }
            .padding()
        }
        .navigationTitle("Transcript")
        .navigationBarTitleDisplayMode(.inline)
        .sheet(item: $selectedTerm) { term in
            GlossaryTermSheet(term: term)
        }
    }

    private var summaryLink: some View {
        NavigationLink {
            TranscriptSummaryView(recording: recording)
        } label: {
            HStack {
                Label("AI Summary", systemImage: "sparkles")
                    .font(.headline)
                    .foregroundStyle(.purple)
                Spacer()
                if recording.summary != nil {
                    Text("View")
                        .foregroundStyle(.secondary)
                } else {
                    Text("Generate")
                        .foregroundStyle(.secondary)
                }
                Image(systemName: "chevron.right")
                    .font(.caption)
                    .foregroundStyle(.tertiary)
                    .accessibilityHidden(true)
            }
            .padding()
            .background(.background)
            .clipShape(RoundedRectangle(cornerRadius: 12))
            .shadow(color: .black.opacity(0.05), radius: 2, y: 1)
        }
        .buttonStyle(.plain)
    }

    private var disclaimer: some View {
        HStack(spacing: 8) {
            Image(systemName: "info.circle.fill")
                .foregroundStyle(.orange)
                .accessibilityHidden(true)
            Text(disclaimerText)
                .font(.caption)
                .foregroundStyle(.secondary)
        }
        .padding()
        .background(Color.orange.opacity(0.08))
        .clipShape(RoundedRectangle(cornerRadius: 10))
    }

    private var disclaimerText: String {
        "This transcript was generated by on-device speech recognition. "
        + "It may contain errors. Always verify important medical information "
        + "with your healthcare provider."
    }

    private var sortedSegments: [TranscriptSegment] {
        recording.segments.sorted { $0.timestamp < $1.timestamp }
    }

    private var fullTranscriptSection: some View {
        VStack(alignment: .leading, spacing: 8) {
            Text("Full Transcript")
                .font(.headline)
            highlightedText(recording.transcriptText)
        }
    }

    private var segmentsSection: some View {
        VStack(alignment: .leading, spacing: 12) {
            Text("Transcript")
                .font(.headline)
            ForEach(sortedSegments) { segment in
                segmentRow(segment)
            }
        }
    }

    private func segmentRow(_ segment: TranscriptSegment) -> some View {
        HStack(alignment: .top, spacing: 12) {
            Text(formatTimestamp(segment.timestamp))
                .font(.caption)
                .foregroundStyle(.secondary)
                .monospacedDigit()
                .frame(width: 44, alignment: .trailing)
            highlightedText(segment.text)
        }
    }

    private func highlightedText(_ text: String) -> some View {
        let matched = matchedTerms(in: text)
        if matched.isEmpty {
            return AnyView(
                Text(text)
                    .font(.body)
            )
        }
        return AnyView(
            HighlightedTranscriptText(
                text: text,
                terms: matched,
                onTermTap: { term in selectedTerm = term }
            )
        )
    }

    private func matchedTerms(in text: String) -> [GlossaryTerm] {
        let lower = text.lowercased()
        return GlossaryContent.allTerms.filter { term in
            lower.contains(term.term.lowercased())
        }
    }

    private func formatTimestamp(_ seconds: TimeInterval) -> String {
        let mins = Int(seconds) / 60
        let secs = Int(seconds) % 60
        return String(format: "%d:%02d", mins, secs)
    }
}


struct HighlightedTranscriptText: View {
    let text: String
    let terms: [GlossaryTerm]
    let onTermTap: (GlossaryTerm) -> Void

    var body: some View {
        Text(buildAttributedString())
            .font(.body)
            .environment(\.openURL, OpenURLAction { url in
                if let termID = url.host(),
                   let term = terms.first(where: { $0.id == termID }) {
                    onTermTap(term)
                }
                return .handled
            })
    }

    private func buildAttributedString() -> AttributedString {
        var attributed = AttributedString(text)
        for term in terms {
            let searchTerm = term.term.lowercased()
            let lower = text.lowercased()
            var searchStart = lower.startIndex
            while let range = lower.range(of: searchTerm, range: searchStart..<lower.endIndex) {
                if let attrRange = Range(range, in: attributed) {
                    attributed[attrRange].foregroundColor = .blue
                    attributed[attrRange].underlineStyle = .single
                    if let url = URL(string: "glossary://\(term.id)") {
                        attributed[attrRange].link = url
                    }
                }
                searchStart = range.upperBound
            }
        }
        return attributed
    }
}
